#!/usr/bin/env python3
"""typemap.txt -> C table of (address, width) leaves inside the loaded data
images (hd_code .data/.rodata, front-end .data/.rodata), for the INTERIM
image swap of the headless build (src/platform/interim_swap.c).

usage: typemap_c.py TYPEMAP OUT.c
"""
import sys

RANGES = [(0x802E8BD0, 0x8030F660), (0x80208040, 0x80210E90)]

leaves = set()
for line in open(sys.argv[1]):
    p = line.split()
    if len(p) < 3:
        continue
    base = int(p[0], 16)
    for leaf in p[3:]:
        off, w = leaf.split(":")
        a = base + int(off, 16)
        w = int(w.rstrip("f"))
        if w in (2, 4, 8) and any(lo <= a and a + w <= hi for lo, hi in RANGES):
            leaves.add((a, w))
with open(sys.argv[2], "w") as f:
    f.write("/* generated by port/tools/typemap_c.py */\n")
    f.write("typedef struct { unsigned addr; unsigned char width; } TmLeaf;\n")
    f.write("const TmLeaf interim_typemap[] = {\n")
    for a, w in sorted(leaves):
        f.write("    {0x%08Xu, %d},\n" % (a, w))
    f.write("    {0, 0}\n};\nconst unsigned interim_typemap_count = %d;\n" % len(leaves))
print("typemap_c: %d leaves" % len(leaves))
