#!/usr/bin/env python3
"""Turn a splat symbol_addrs file into a linker script of absolute symbols.

Used by `make extract` for hd_front_end: its splat run sees hd_code's names
(symbol_addrs.hd_code), so its .s files call e.g. osInvalDCache by name, and
the front-end link needs those names defined at hd_code's addresses.

  segsyms.py symbol_addrs.hd_code.us.v11.txt --exclude 0x801E7000:0x8021ED00
"""
import argparse, re, sys

ap = argparse.ArgumentParser()
ap.add_argument("symfile")
ap.add_argument("--exclude", action="append", default=[], help="LO:HI address range to leave out (the segment's own)")
a = ap.parse_args()
ranges = [tuple(int(x, 0) for x in r.split(":")) for r in a.exclude]
print("/* generated by tools_port/segsyms.py from %s; do not edit */" % a.symfile)
for line in open(a.symfile):
    m = re.match(r"\s*([A-Za-z_][A-Za-z0-9_.$]*)\s*=\s*(0x[0-9A-Fa-f]+)\s*;", line)
    if not m:
        continue
    addr = int(m.group(2), 16)
    if any(lo <= addr < hi for lo, hi in ranges):
        continue
    print("%s = 0x%08X;" % (m.group(1), addr))
