#!/usr/bin/env python3
"""Filter another segment's splat symbol_addrs file for use in this segment.

Used by `make extract` for hd_front_end, whose splat run also sees hd_code's
names (so its .s files call e.g. osRecvMesg by name):
  --splat: print the kept lines unchanged (appended to symbol_addrs_auto)
  default: print them as absolute linker-script assignments, so the front-end
           link resolves those names at hd_code's addresses
Entries inside an --exclude range (the segment's own vram) and names that the
segment defines itself (--drop-names, its own symbol_addrs) are left out, so
a front-end copy of an SDK function can share its hd_code twin's name.

  segsyms.py symbol_addrs.hd_code.us.v11.txt --exclude 0x801E7000:0x8021ED00 \
      --drop-names symbol_addrs.hd_front_end.us.v11.txt [--splat]
"""
import argparse, re

SYM = re.compile(r"\s*([A-Za-z_][A-Za-z0-9_.$]*)\s*=\s*(0x[0-9A-Fa-f]+)\s*;")
ap = argparse.ArgumentParser()
ap.add_argument("symfile")
ap.add_argument("--exclude", action="append", default=[], help="LO:HI address range to leave out")
ap.add_argument("--drop-names", action="append", default=[], help="symbol_addrs file whose names to leave out")
ap.add_argument("--splat", action="store_true", help="output splat symbol_addrs lines instead of ld assignments")
a = ap.parse_args()
ranges = [tuple(int(x, 0) for x in r.split(":")) for r in a.exclude]
drop = set()
for f in a.drop_names:
    for line in open(f):
        m = SYM.match(line)
        if m:
            drop.add(m.group(1))
tag = "//" if a.splat else "/*"
print("%s generated by tools_port/segsyms.py from %s; do not edit%s" % (tag, a.symfile, "" if a.splat else " */"))
for line in open(a.symfile):
    m = SYM.match(line)
    if not m:
        continue
    addr = int(m.group(2), 16)
    if m.group(1) in drop or any(lo <= addr < hi for lo, hi in ranges):
        continue
    print(line.rstrip("\n") if a.splat else "%s = 0x%08X;" % (m.group(1), addr))
