#ifndef GAME_VARIABLES_H
#define GAME_VARIABLES_H

/*
 * Every game variable used by more than one file, declared once. Most are
 * absolute symbols (undefined_syms*.txt) at their N64 addresses; a few are
 * defined by a game file. The types follow the code's real use; a file that
 * reads one differently says so where it does (a view macro in NON_MATCHING
 * code, or a LEGACY_ declaration the matching build keeps for IDO).
 * Generated by scratchpad types_genvar.py.
 */

/* low memory and others */
extern s32 D_80000300; /* osTvType */

/* hd_code .text (tables inside the code) */
extern u8 D_802C2190[]; /* keys of its three sound entries */
extern u8 D_802C21A4[];
extern u8 D_802C21B8[];
extern u8 D_802C2208[]; /* keys of this vehicle's func_802A06B4 entries */
extern u8 D_802C226C[];
extern u8 D_802C28E4[]; /* effect definitions in the 7D9D0 text blob */
extern u8 D_802C2954[]; /* definition handed to func_802A6274 (7D9D0 text blob) */
extern u8 D_802C2984[]; /* definition handed to func_802A6274 (7D9D0 text blob) */
extern u8 D_802C3804[]; /* definition handed to func_802A6274 */
extern u8 *D_802C3FFC[]; /* definition pointers, in the 7D9D0 text blob */
extern u8 D_802E6820[]; /* RSP boot ucode, ends at D_802E68F0 */
extern u8 D_802E68F0[];

/* front end .data / .bss (0x80208040-0x8021ED00) */
extern u8 D_802082B8[0x20]; /* number of words on the rank name's first line */
extern u8 D_802154B0;
extern u8 *D_80215A7C; /* glow textures */
extern u8 *D_80215A80;
extern u8 *D_80215A84;
extern s32 D_80217B6C; /* camera node */
extern Mtx D_802182D0[];
extern u8 D_80218EE0[];
extern OSMesgQueue D_80219EF8; /* requests to the pak/EEPROM thread */
extern OSMesgQueue D_80219F50; /* pakToGameMessageQ */
extern u64 D_8021A830;
extern u8 D_8021A8F0;
extern f32 D_8021A918;
extern f32 D_8021A91C;
extern f32 D_8021A920;

/* hd_code .data / .rodata (0x802E8BD0-0x8030F660) */
extern u8 D_802E8BD0;
extern u8 D_802E8BD4;
extern u8 D_802E8BD8;
extern u8 D_802E8BE4; /* screen shake time */
extern s32 D_802E8BE8; /* screen shake size */
extern s32 D_802E8BEC;
extern u8 D_802E8BF0;
extern u8 D_802E8BF8;
extern u8 D_802E8C44[];
extern f32 D_802E8C84[]; /* per-font advance */
extern u16 D_802E8C8C[]; /* per-font characters that draw nothing */
extern u16 D_802E8C90[];
extern u16 D_802E8C94[];
extern u16 D_802E8C98[]; /* string terminator */
extern u8 D_802F4868[];
extern u8 D_802F4870[];
extern s32 D_802FA254; /* -d */
extern s32 D_802FA264; /* debug mode */
extern s32 D_802FA268; /* -c, -C */
extern s32 D_802FA26C; /* -C */
extern Vtx D_802FA8B0[][4];
extern u8 D_802FA940[]; /* 32x32 IA8 texture */
extern u8 D_802FAD50[]; /* 32x32 RGBA32 frame texture */
extern u8 D_802FDB14;
extern u8 D_802FDBD0;
extern u8 D_802FDBD4;

/* hd_code .bss (0x8030F660-0x80400000) */
extern OSMesgQueue D_803150A0;
extern OSMesgQueue D_80315180; /* texture DMA queue */
extern u32 D_803156C0; /* frame counter */
extern u32 D_803156C4;
extern u8 D_803156F4;
extern u8 D_8035805C; /* selects which of the two matrix buffers is current */
extern u32 D_80358060; /* frame counter */
extern s32 D_80358064;
extern s32 D_80358068;
extern s32 D_80358078; /* top-level display list length */
extern u16 D_8035807C; /* projection scale, 65535 = 1.0 */
extern s32 D_80358080; /* queued-DMA counter (next OSIoMesg slot) */
extern s32 D_80358084; /* no_palette_dmas */
extern u8 D_803643D4;
extern u8 D_803643D5;
extern u8 D_803643D6;
extern u8 D_803643D7;
extern u8 D_803643D8;
extern u8 D_803643D9;
extern u8 D_803643DA;
extern u8 D_803643DB;
extern u8 D_803643DC;
extern s32 D_803643E0; /* player position, speed, heading, angle */
extern s32 D_803643E4;
extern s32 D_803643E8; /* player z */
extern s32 D_803643F8; /* listener x, y, z (<< 11) */
extern s32 D_803643FC;
extern s32 D_80364400;
extern s32 D_80364404; /* fixed eye x, y, z */
extern s32 D_80364408;
extern s32 D_8036440C;
extern u8 D_80364410;
extern u8 D_80364411;
extern u8 D_80364412; /* camera: snap to the new position this frame */
extern f32 D_80364414; /* camera heading, degrees */
extern u8 D_80364424;
extern u32 D_80364428;
extern u16 D_8036442C;
extern s32 D_80364430;
extern f32 D_80364438;
extern s16 D_8036443C; /* player speed, heading, angle */
extern s16 D_8036443E; /* camera yaw, 4095 = 360 degrees */
extern s16 D_80364440;
extern s16 D_8036444C;
extern s16 D_8036444E;
extern s16 D_80364450;
extern s16 D_80364452; /* camera / player angle (0..0xFFF) */
extern u8 D_80364456; /* mode: the update is skipped in modes 0,1,2,6,7,9,0xB,0x10..0x12 */
extern u64 D_803649D8; /* frame counter */
extern s16 D_803649E0; /* x, y, z stored for a part that falls */
extern s16 D_803649E2;
extern s16 D_803649E4;
extern u8 D_803649ED;
extern u8 D_803649EE;
extern u32 D_803649F0; /* score */
extern s32 D_80364A40; /* message to post */
extern u8 D_80364A50;
extern s32 D_80364A58;
extern s32 D_80364A64;
extern u8 D_80364A68; /* dial loaded */
extern u8 D_80364A69;
extern u8 D_80364A6A; /* icon 1 loaded */
extern u8 D_80364A6B;
extern u8 D_80364A6C; /* icon 2 loaded */
extern u8 D_80364A6D;
extern u8 D_80364A6E; /* default level */
extern s8 D_80364A71;
extern s16 D_80364A72; /* tilt limits */
extern u8 D_80364A84;
extern u8 D_80364A87;
extern u64 D_80364A88; /* previous game mode */
extern u64 D_80364A90; /* game mode flags */
extern u64 D_80364A98; /* next game mode */
extern u32 D_80364AA8; /* game mode flags */
extern u8 D_80364AC1;
extern u8 D_80364AE8; /* current player */
extern u8 D_80364AE9;
extern u8 D_80364AEA;
extern u16 D_80364EF0[][16]; /* per player: saved level times */
extern u16 D_80364F70[]; /* EEPROM best-time words (time, time ^ 0x55AA) */
extern u8 D_80365060[]; /* per slot: 0 no save, 1 saved game, 2 new game */
extern u8 D_80365580;
extern u8 D_8036698C;
extern s32 D_803669B4;
extern u8 *D_803669C0; /* input buffer */
extern u8 *D_803669C4; /* output buffer */
extern s32 D_803669EC; /* inptr */
extern s32 D_803669F0; /* outcnt */
extern s16 D_80366A04;
extern u16 D_80366A12;
extern u8 D_80366A18;
extern u8 D_80367728;
extern u8 D_80367729;
extern u8 D_8036772A;
extern s32 D_8036772C;
extern u8 D_80367730;
extern u32 D_80367740;
extern u16 D_80367BC8;
extern s16 D_80367BD6; /* HUD alpha cap */
extern u16 D_80367BF6;
extern u8 D_80367BFF;
extern u8 D_80367C00;
extern u8 D_80367C10;
extern s32 D_80368030;
extern s32 D_80368040;
extern s32 D_80368048;
extern u8 D_8036B8B0;
extern s32 D_8036B8B4;
extern s32 D_8036B8B8;
extern s32 D_8036B8BC;
extern u8 D_8036B964;
extern u8 D_8036B965;
extern s32 D_8036B968;
extern u8 D_8036B971;
extern char D_8036B9A8[]; /* status screen lines, 0x20 each */
extern u16 D_8036BB16;
extern s16 D_8036BB1A;
extern s16 D_8036BB1E;
extern s16 D_8036BB20;
extern f32 D_8036BB34;
extern u16 D_8036BBB0[];
extern s32 D_8036BF10;
extern OSTime D_8036BF38;
extern s32 D_8036C7C8; /* time left; under 500 the target turns red */
extern u8 D_8036C7CC;
extern s16 D_8036CB2A;
extern s16 D_8036CB2C;
extern u8 D_8036CB2E;
extern u8 D_8036CB2F;
extern u8 D_8036DCD4; /* level has water */
extern u8 D_8036DCD7;
extern s32 D_8036DCD8;
extern s16 D_8036E4C8;
extern s8 D_8036E4CA;
extern u8 D_8036E68C[]; /* slot busy flags */
extern u8 D_8036EA78;
extern u8 D_8036EA79;
extern u16 D_8036EA7C;
extern u16 D_8036EB90;
extern u8 D_8036EB92;
extern u8 D_8036EB93;
extern u8 D_8036EB98;
extern u8 D_8036EB99;
extern OSMesgQueue D_80370BF8; /* hd_code: SI message queue */
extern s8 D_80370C11;
extern s8 D_80370C12;
extern s8 D_80370C13;
extern s8 D_80370C14;
extern u8 D_80370C15; /* button bytes */
extern u8 D_80370C16; /* R_JPAD */
extern u8 D_80370C1A; /* flags (either one set animates) */
extern u8 D_80370C1B; /* input 1 */
extern u8 D_80370C1C; /* flag tested when the speed is <= 0 */
extern u8 D_80370C1D; /* B */
extern u8 D_80370C1E; /* L_CBUTTONS */
extern u8 D_80370C21; /* R_CBUTTONS */
extern u8 D_80370C22; /* Z */
extern u8 D_80370C23; /* flag tested when the speed is > 0 */
extern u8 D_80370C24;
extern u8 D_80370C27;
extern u16 D_80370C28; /* controller buttons held */
extern u16 D_80370C2A; /* controller buttons, previous frame */
extern s8 D_80370C2C; /* flag sampled each counted frame */
extern s8 D_80370C2D; /* stick y */
extern s8 D_80370C2E; /* stick x last frame */
extern u16 D_80370C30; /* controller 1 buttons */
extern s8 D_80370C32; /* controller 1 stick x */
extern s8 D_80370C33; /* controller 1 stick y */
extern u8 D_80370C34;
extern u8 D_80370C35; /* stick mode */
extern s32 D_80370C38; /* swallow a held B */
extern u8 D_80370C50; /* front end loaded */
extern OSIoMesg D_80370C58;
extern u16 D_80370C70;
extern s16 D_80370C72;
extern u8 D_80370C75;
extern u8 D_8039C4B0; /* pak thread busy */
extern u8 D_8039C538;
extern u8 D_8039C53C[]; /* per slot: 1 + level to save, 0 = nothing pending */
extern u8 D_8039C540;
extern u8 D_8039C541;
extern u8 D_8039C940; /* number of D_8039C800 entries */
extern u8 D_8039CA60;
extern u8 D_8039CA61;
extern u8 D_8039CA62;
extern u8 D_8039CA7E;
extern s16 D_8039CAA0;
extern u8 D_8039CAA2;
extern s16 D_8039CAB0;
extern s16 D_8039CAB2;
extern s16 D_8039CAB4;
extern u8 D_8039CAB6;
extern u8 D_8039CAB7;
extern s32 D_8039CAE0; /* huft arena */
extern u8 D_803A6B04;
extern u8 D_803A7300[]; /* 0x14-byte vehicle spheres: x, y, z, r words, byte 0x10 = kind, 0x11 = state (0xFF = end) */
extern s32 D_803A73F0; /* a point x, z (16.16-ish; the part position is << 5) */
extern s32 D_803A73F4;
extern s32 D_803A73F8;
extern s32 D_803A740C; /* frame stamp */
extern s16 D_803A7410; /* ring index A (12-bit, see func_8029B930) */
extern s16 D_803A7412; /* ring index B */
extern u8 D_803A7424;
extern u8 D_803A7425;
extern s8 D_803A7426;
extern u8 D_803A7427;
extern u8 D_803A742A;
extern u8 D_803A742B;
extern u8 D_803A742F;
extern u8 D_803A7430;
extern u8 D_803B9888; /* the table below is loaded */
extern u8 D_803BC1D0[]; /* 0xDC-byte groups */
extern u8 *D_803BD300; /* end of the D_803B9890 records */
extern u8 *D_803BD304; /* end of the groups in use */
extern u8 *D_803BD308; /* triangle range */
extern u8 *D_803BD30C;
extern u8 D_803BD310[]; /* 0xFC-byte switch groups: kind count at 0, kinds from 1, tri pointers from 8 (count at 0xF8), flag 0xF9 */
extern u8 *D_803BDAF4; /* 0x14-byte triangles (as func_802AA094's) */
extern u8 *D_803BDAF8; /* their end */
extern u8 *D_803BDB10[]; /* per-cell triangle lists (cell i spans [i] .. [i + 1] - 4) */
extern u8 *D_803BDCA8[];
extern u8 *D_803BDE40[]; /* per-cell triangle lists (cell c spans [c] .. [c + 1]) */
extern u8 *D_803BDFD4; /* end of the zone list that starts at D_803BDFD8 */
extern u8 D_803BDFD8[]; /* 0x24-byte zones: s32 x, y, z, radius; u8 flags at +0x10.. */
extern u8 *D_803BE6F8; /* 9-byte respawn records: u8 key, s16 x, y, z (big-endian) */
extern u8 *D_803BE708;
extern s32 D_803BE70C;
extern s32 D_803BE710;
extern s16 D_803BE714;
extern u16 D_803BE716;
extern u32 D_803BE718; /* grid cell width */
extern u32 D_803BE71C; /* grid cell depth */
extern u16 D_803BE720; /* grid columns */
extern u16 D_803BE722;
extern s32 D_803BE724;
extern s32 D_803BE728;
extern s16 D_803BE72C;
extern s16 D_803BE730; /* level box: x min, x max, z min, z max (>> 5 units) */
extern s16 D_803BE732; /* level extent x, z (>> 5) */
extern s16 D_803BE734;
extern s16 D_803BE736;
extern u8 D_803BE738;
extern u8 D_803BE739;
extern u8 D_803BE73A; /* current level index */
extern u16 D_803C30A8[]; /* visible object ids, ended by -1 */
extern Gfx D_803C5770[]; /* display lists A / B, frame 0 */
extern Gfx D_803C6370[]; /* display lists A / B, frame 1 */
extern Gfx D_803C6F70[];
extern Gfx D_803C7B70[];
extern u8 *D_803EBBEC; /* end of the used D_803EBDB0 records */
extern f32 D_803EBBF0;
extern f32 D_803EBBF4;
extern s32 D_803EBBF8;
extern s32 D_803EBBFC; /* height of func_802AC0BC's best triangle */
extern u8 D_803EBC10[]; /* 0x10-byte records, id byte at +0xC */
extern u8 D_803EBDB0[]; /* 0x38-byte triangle records, u16 id at +0x36 */
extern s16 D_803ED392; /* rotation angle y (x and z: D_803ED390, D_803ED394_) */
extern u8 D_803ED3B8[]; /* 4-byte records {u8 key, u8 kinds[3]}, word -1 ends */
extern u8 D_803ED3F5;
extern u8 D_803ED3F6;
extern u8 D_803ED3F7;
extern s16 D_803ED400;
extern s16 D_803ED408;
extern u8 D_803ED40A;
extern u8 D_803ED40B;
extern u8 D_803ED40C;
extern u8 D_803ED40D;
extern u8 D_803ED40F;
extern s32 D_803ED80C;
extern s32 D_803ED810;
extern u8 D_803ED825; /* drive-in enabled */
extern u8 D_803ED826; /* drive-in active */
extern s16 D_803EDC00; /* horn uses left */
extern u8 D_803EE3B1; /* dial value, 0..100 */
extern s32 D_803EF2EC; /* sound source x, y, z */
extern s32 D_803EF2F0;
extern s32 D_803EF2F4; /* z */
extern s32 D_803EF304; /* result height (world units) */
extern s32 D_803EF308; /* marker x, z (y = 0) */
extern s32 D_803EF30C;
extern s32 D_803EF310; /* marker position x, y, z, w */
extern s32 D_803EF314;
extern s32 D_803EF318;
extern s16 D_803EF326;
extern s16 D_803EF328;
extern s16 D_803EF32A;
extern u8 D_803EF32C;
extern u8 D_803EF32D;
extern u8 D_803EF32E;
extern s32 D_803EF6DC; /* sound source x, y, z */
extern s32 D_803EF6E0;
extern s32 D_803EF6E4;
extern s32 D_803EF6F0;
extern s32 D_803EF6F8;
extern s16 D_803EF6FC; /* divisor, 0 = none */
extern u8 D_803EF6FF; /* effect finished */
extern s32 D_803EFEB0; /* x interpolation: x0, x1 */
extern s32 D_803EFEB4; /* z interpolation: z0, z1 */
extern s32 D_803EFEB8;
extern s32 D_803EFEBC;
extern u8 D_803EFEC8; /* x follows z along the line (D_803EFEB0..) */
extern u8 D_803EFECB;
extern u8 D_803F0900[]; /* 4 entries of 0x4B8 bytes */
extern u8 D_803F1BE0[]; /* 2 entries of 0x478 bytes */
extern u8 D_803F3910[];
extern s32 D_803F7660;
extern s32 D_803F7664; /* position objects with a pose are moved to */
extern s32 D_803F7668;
extern s32 D_803F766C;
extern s32 D_803F7670; /* player x */
extern s32 D_803F7674;
extern s32 D_803F7678; /* player z */
extern s16 D_803F767C;
extern s16 D_803F767E;
extern s16 D_803F7680;
extern s32 D_803F7684;
extern s32 D_803F7688;
extern s32 D_803F77F8;
extern s16 D_803F77FC; /* signed input whose sign is tracked */
extern u8 D_803F7801;
extern u8 D_803F7804;
extern u8 D_803F7805; /* request flag, consumed here */
extern u8 D_803F7806;
extern u8 D_803F7808;
extern u8 D_803F7809; /* kind of the target (as D_803F7808: 2 and 3 have pos at +0) */
extern u8 D_803F780A; /* last sign of D_803F77FC (-1, 0, 1) */
extern u8 D_803F780B; /* run length, 0..0x14 */
extern u8 D_803F780C; /* result: set for one call when a run of 0x14 completes with a change */
extern u8 D_803F7810;
extern u8 D_803F7812;
extern u8 *D_803F782C; /* its end */
extern s16 D_803F7840; /* last |level| set by func_802C4584 (-1 = none yet) */
extern s32 D_803F7C10;
extern s32 D_803F7C14;
extern s16 D_803F7C34;
extern u8 D_803F7C3F;
extern u8 D_803F7C49;
extern s16 D_803F8B72; /* horn presses left */
extern s32 D_803F9320;
extern s32 D_803F9324;
extern u8 D_803F932C;
extern u8 D_803F932D;
extern u8 D_803F932E;
extern u8 D_803F9330[]; /* 0x60-byte triangles */
extern u8 D_803FC1F0; /* current box index */
extern s32 D_803FCD48; /* sound source x, y, z */
extern s32 D_803FCD4C;
extern s32 D_803FCD50;
extern s32 D_803FCD60;
extern s16 D_803FCD68;
extern s16 D_803FCD6A; /* angles x, y, z */
extern s16 D_803FCD6C;
extern s16 D_803FCD6E;
extern u8 D_803FCD70; /* event this frame */
extern u8 D_803FCD75; /* sound mode: 0 or 1 */

/* ROM addresses (DMA sources) */
extern u8 D_0048F5A0[];
extern u8 D_0066C900[]; /* worldtextures */
extern u8 D_0068B550[]; /* ... its end */
extern u8 D_006A32B0[];
extern u8 D_006A8DA0[];
extern u8 D_006A9F10[];
extern u8 D_006AD3F0[]; /* compressed pictures (ROM) */
extern u8 D_006E8980[];

/* segment addresses */
extern Gfx D_01000010[]; /* segment 1 */
extern Gfx D_01000038[];

/* named */
extern s16 currentYoshiWindow;
extern s16 yoshiState;

#endif
