#include "common.h"
#include <ultra64.h>

/* TODO: func_8025C5D0 - a switch on D_802E8BEC (0..8, default no-op)
 * dispatching into per-case chains of "if (D_80358060 == CONST)
 * func_8026AF6C(errCode);" assertion-style checks (case 0 is the
 * largest, gated on D_80364A90==0 && D_80364A94==2 picking between two
 * different sets of constants/error codes), then a shared tail that
 * sets D_80366A18=1 if D_80358060==0x82. Every case, constant, and
 * error code is confirmed correct by direct transcription. The blocker
 * isn't logic - it's that target compiles this via a real indirect
 * jump through a 9-entry rodata jump table (jtbl_80309070, a fixed ROM
 * address this project already treats as a pre-existing data symbol),
 * and this project's hd_code linker script (auto-generated by splat
 * from the segment yaml) places no .rodata output section for any
 * hd_code .c file - every other matched function only ever needed
 * .text. A `switch` here makes IDO emit a fresh compiler-generated jump
 * table, which the linker then discards for having nowhere to go
 * ("defined in discarded section"), and an if/else-if chain compiles to
 * sequential branches instead of a jr-through-jtbl, which can't be
 * byte-identical to a true jump table regardless of condition order.
 * Needs a build-system change (teaching the yaml/ld generation about a
 * .rodata output for this file) before a source-level attempt is
 * worthwhile. */
#pragma GLOBAL_ASM("asm/nonmatchings/hd_code/17E10/func_8025C5D0.s")

#pragma GLOBAL_ASM("asm/nonmatchings/hd_code/17E10/func_8025C878.s")

extern void *D_80358070;
extern void *D_80366BA0;
extern void *D_80366BA4;

void func_8025CE74(void) {
    D_80366BA0 = D_80358070;
    D_80358070 = (u8 *) D_80366BA0 + 0x40;

    *(u16 *) ((u8 *) D_80366BA0 + 0x0) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0x2) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0x4) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0x6) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0x8) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0xa) = 0x9e0;
    *(u8 *)  ((u8 *) D_80366BA0 + 0xc) = 0;
    *(u8 *)  ((u8 *) D_80366BA0 + 0xd) = 0;
    *(u8 *)  ((u8 *) D_80366BA0 + 0xe) = 0;
    *(u8 *)  ((u8 *) D_80366BA0 + 0xf) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0x10) = 0x14;
    *(u16 *) ((u8 *) D_80366BA0 + 0x12) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0x14) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0x16) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0x18) = 0x280;
    *(u16 *) ((u8 *) D_80366BA0 + 0x1a) = 0x9e0;
    *(u8 *)  ((u8 *) D_80366BA0 + 0x1c) = 0;
    *(u8 *)  ((u8 *) D_80366BA0 + 0x1d) = 0;
    *(u8 *)  ((u8 *) D_80366BA0 + 0x1e) = 0;
    *(u8 *)  ((u8 *) D_80366BA0 + 0x1f) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0x20) = 0x14;
    *(u16 *) ((u8 *) D_80366BA0 + 0x22) = 0x4f;
    *(u16 *) ((u8 *) D_80366BA0 + 0x24) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0x26) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0x28) = 0x280;
    *(u16 *) ((u8 *) D_80366BA0 + 0x2a) = 0;
    *(u8 *)  ((u8 *) D_80366BA0 + 0x2c) = 0;
    *(u8 *)  ((u8 *) D_80366BA0 + 0x2d) = 0;
    *(u8 *)  ((u8 *) D_80366BA0 + 0x2e) = 0;
    *(u8 *)  ((u8 *) D_80366BA0 + 0x2f) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0x30) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0x32) = 0x4f;
    *(u16 *) ((u8 *) D_80366BA0 + 0x34) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0x36) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0x38) = 0;
    *(u16 *) ((u8 *) D_80366BA0 + 0x3a) = 0;
    *(u8 *)  ((u8 *) D_80366BA0 + 0x3c) = 0;
    *(u8 *)  ((u8 *) D_80366BA0 + 0x3d) = 0;
    *(u8 *)  ((u8 *) D_80366BA0 + 0x3e) = 0;
    *(u8 *)  ((u8 *) D_80366BA0 + 0x3f) = 0;

    D_80366BA4 = D_80358070;
    D_80358070 = (u8 *) D_80366BA4 + 0x780;
}

/* TODO: func_8025D0B0 - for arg0==0, load a (baseAddr=0x487050,
 * size=0x2E20) pair; for arg0==1, (0x489E70, 0x5730) (0x489E70 is both
 * mode 0's end and mode 1's start - these read like adjacent slots in a
 * ROM resource table, each size = next_start - this_start); call
 * func_8028B4C4(baseAddr, D_80358070, &size, 0xc), then set
 * D_80366BB0[arg0] = D_80358070 & 0x1FFFFFFF and bump D_80358070 by size.
 * Logic and every field/offset are confirmed correct (every phrasing tried
 * lands on the right values) - two compiler-behavior gaps block a match
 * rather than any logic error. First: this compiler constant-folds
 * `end - baseAddr` into a single `li` the moment both operands are
 * literal-initialized locals in the same block, while target has a real
 * runtime `subu` of two lui/addiu-built registers - tried separating them
 * into distinct named locals (still folds) and `volatile` (stops the fold
 * but adds load/store pairs target doesn't have either). Second: target
 * keeps arg0 live in the callee-saved $s0 across the whole function
 * (saved/restored around the one call) instead of reloading its stack
 * byte 3 times like every C phrasing produces; `register` on the
 * parameter had no effect. Likely needs direct evidence of which pass
 * made each choice (decomp-workbench's register-role-audit) rather than
 * more source guessing. */
#pragma GLOBAL_ASM("asm/nonmatchings/hd_code/17E10/func_8025D0B0.s")

#pragma GLOBAL_ASM("asm/nonmatchings/hd_code/17E10/func_8025D184.s")

#pragma GLOBAL_ASM("asm/nonmatchings/hd_code/17E10/func_8025D2B4.s")

extern Mtx D_02000000[];
void func_8024FC2C(Gfx **, s32);

void func_8025E1E0(Gfx **arg0) {
    Gfx *gfx = *arg0;

    gSPMatrix(gfx++, &D_02000000[2], G_MTX_PROJECTION | G_MTX_LOAD | G_MTX_NOPUSH);
    gSPMatrix(gfx++, &D_02000000[5], G_MTX_PROJECTION | G_MTX_MUL | G_MTX_NOPUSH);
    gSPMatrix(gfx++, &D_02000000[7], G_MTX_MODELVIEW | G_MTX_LOAD | G_MTX_NOPUSH);
    func_8024FC2C(&gfx, 0);
    func_8024FC2C(&gfx, 1);
    func_8024FC2C(&gfx, 2);
    *arg0 = gfx;
}

/* TODO: func_8025E2CC - an *arg0-output state machine gated on
 * D_803643D7 and func_802753C0()==0: on D_80366BC0==0, checks whether
 * D_802E8F94[D_802E8BDC*68] is 0x20 or 0x80 (calls func_802C1DD0 with
 * that bool), then checks a flag byte at D_80364AF0[(D_80364AE8<<8)+
 * D_802E8BDC+0x18] against the range (0,6) to pick between a "normal"
 * branch and a dispatch on D_802E8BDC (cases 0x28, 0x32, default) that
 * each set D_80366BC2 (an event code)/D_80366BC4 (a flag) and call a
 * couple of func_80260xxx helpers, then posts the event via
 * func_8026AF6C(D_80366BC2|0xa000) and, if the code was 5, calls
 * func_80260650 with a func_8026205C(2) result. Falls through to a
 * tail that re-arms D_80366BC0, and on D_80366BB8==0 either rematerializes
 * it from D_803156C4 (if a specific D_8036BB1C/D_8036BB18 == D_80366BC2
 * condition holds) or, on D_80366BB8!=0, decides via a
 * func_802D4E10/D_80366BC4/timestamp-delta chain whether to call
 * func_80275270(0, 0x08000000, 0x3f400000) and zero D_80366BB8/
 * D_80366BC0. Logic, every field, offset, and branch condition are
 * confirmed correct by direct transcription (down to a frame that
 * matches target exactly at -40, 237 vs 236 target instructions - the
 * closest build reached deficit 9). The blocker is register allocation,
 * not logic: target keeps the "flag" value live in the callee-saved
 * $s0 continuously across almost the entire function - reused directly
 * as a call argument, as a branch-compare operand, and as the
 * dispatch key - never spilling or reloading it even across the many
 * intervening calls, while every C phrasing tried (plain reassignment,
 * `register`, combining the two early boolean checks into `||`/`&&`
 * expressions, a `switch` for the 0x28/0x32/default dispatch) either
 * leaves it stack-homed with explicit reload instructions or, when
 * `register` is added, promotes it along with something else into an
 * extra $s1 save instead of just $s0 (frame grows from -40 to -56
 * either way). The `switch` rewrite for the dispatch alone did get the
 * closest on raw opcode distance, suggesting the real source may have
 * used one there, but didn't fix the two earlier checks' spills and
 * regressed the frame, so it wasn't kept. */
#pragma GLOBAL_ASM("asm/nonmatchings/hd_code/17E10/func_8025E2CC.s")

#pragma GLOBAL_ASM("asm/nonmatchings/hd_code/17E10/func_8025E67C.s")

/* TODO: func_8025EDF0 - links arg0->unk8 into D_802E8CEC->0x48, resets
 * D_802E8CEC->0x40 and sets ->0x4c=0x80e8; allocates arg0->unk0*0x40
 * bytes via func_802D6B10 into D_802E8CEC->0x44 and D_802E8CE8, then
 * arg0->unk4*28 bytes into func_802D6E3C(D_802E8CEC+0x14, ., arg0->unk4);
 * for i=1..arg0->unk0-1, calls func_802D6EE0 on 0x40-byte slices of the
 * first allocation; allocates arg0->unk10 u16s into D_80366C28 and fills
 * them with 0x7fff; sets D_802E8CEC->0x38=D_803065C0, ->0=0, ->8=the
 * function pointer func_8025F044, ->4=itself (a self-referential node),
 * calls func_802D6F70(->0x38, D_802E8CEC), posts a {code=0x20} event via
 * func_802D6C8C with D_802E8CEC->0x4c as the extra field, then sets
 * D_802E8CEC->0x50 = func_802D6DB0(D_802E8CEC+0x14, D_802E8CEC+0x28).
 * Logic and every field/offset are confirmed correct (down to 2
 * differing opcodes with the frame, instruction count and nearly every
 * register already exact). The one gap: in the first counted loop,
 * target computes the incremented index straight into the register it
 * reuses for the bound check (`addiu t2,t1,1; sw t2,...; ...; sltu
 * at,t2,t4`), while a plain `i = i + 1;` statement here always reloads i
 * fresh for the following while-test. Folding the increment into the
 * while-condition itself - `while ((i = i + 1) < bound)`, the exact
 * lever that fixed this same gap in func_80260210 and the retried
 * func_80260A30 - backfires here instead: since `i` is also read inside
 * the loop body's own call arguments, IDO promotes it to a callee-saved
 * $s-register across the whole loop (save-slots go from 4 to 12 bytes),
 * which is worse. Left as the plain two-statement form. */
#pragma GLOBAL_ASM("asm/nonmatchings/hd_code/17E10/func_8025EDF0.s")

/* TODO: func_8025F044 - repeat {if entry->unk28==0x20, post a {code=0x20,
 * param=entry+0x14} event with entry->unk4c as the 3rd field, else call
 * func_8025F0F0(entry, entry+0x28); then entry->unk50 =
 * func_802D6DB0(entry+0x14, entry+0x28)} until unk50 becomes nonzero, then
 * entry->unk54 += unk50 and return unk50 (a polling/retry loop with a
 * fixed `entry`, never advancing - the retries are driven entirely by the
 * three calls' side effects). Logic, every field offset, and the loop
 * condition are all confirmed correct (diff score down to 460, frame size
 * exact, zero inserts/deletes) - the one gap: inside the `unk28==0x20`
 * branch, target reloads `entry` from its stack home a second time right
 * before using it for the call's a0/a2 despite having just loaded it for
 * the preceding comparison, while every phrasing tried keeps reusing the
 * already-loaded register instead, cascading into register-rename diffs
 * for the rest of the function. Tried moving the inner `eventCode` local
 * to function scope; no effect (score 462, same shape). */
#pragma GLOBAL_ASM("asm/nonmatchings/hd_code/17E10/func_8025F044.s")

#pragma GLOBAL_ASM("asm/nonmatchings/hd_code/17E10/func_8025F0F0.s")

extern void *D_802E8CEC;

void func_802D74E0(s32, void *);
void func_802D7560(s32, void *);
void func_80260148(void *, void *, u16);

void func_8026005C(void *arg0) {
    if (*((u8 *) arg0 + 0x3e) & 4) {
        func_802D74E0(*(s32 *) ((u8 *) D_802E8CEC + 0x38), (u8 *) arg0 + 0xc);
        func_802D7560(*(s32 *) ((u8 *) D_802E8CEC + 0x38), (u8 *) arg0 + 0xc);
    }
    func_802604FC(arg0);
    func_80260148((u8 *) D_802E8CEC + 0x14, arg0, 0xffff);
}

/* TODO: func_802600D8 - looks up arg0->unk8->unk4->unk5 (a signed byte),
 * passes it to func_802D7610 (a float-returning lookup/conversion), scales
 * the result by arg0->unk2c, and posts a {code=0x10, param=arg0, extra=the
 * scaled float's raw bits} event via func_802D6C8C. Logic, the pointer
 * chase, and the event-struct field layout are all confirmed correct
 * (diff score down to 675, zero logic errors). The one gap: this compiler
 * always promotes a float local to a callee-saved register ($f20, with a
 * matching sdc1/ldc1 prologue/epilogue save) the moment its address is
 * taken to read its bits as an integer, even when - as here - the value is
 * fully consumed well before any later call and a bare stack home would
 * suffice; target has no such save at all. Tried: reordering the
 * assignments every way, `register` (illegal combined with `&`), and a
 * union in place of the pointer-cast reinterpret (same promotion either
 * way) - this looks like a blanket cfe rule for address-taken floats, not
 * something a source rephrasing routes around. */
#pragma GLOBAL_ASM("asm/nonmatchings/hd_code/17E10/func_802600D8.s")

s32 func_802D6EB0(void *);
s32 func_802D6EE0(void *, void *);
s32 func_802D7660(s32);

void func_80260148(void *arg0, void *arg1, u16 arg2) {
    void *list;
    void *next;
    void *entry2;
    void *dup;
    void *addr;
    s32 savedState;

    savedState = func_802D7660(1);
    list = *(void **) ((u8 *) arg0 + 8);
    while (list != NULL) {
        next = *(void **) list;
        addr = (u8 *) list + 0xc;
        entry2 = list;
        dup = next;

        if (*(void **) ((u8 *) list + 0x10) == arg1) {
            if ((*(u16 *) ((u8 *) list + 0xc) & arg2) != 0) {
                if (next != NULL) {
                    *(s32 *) ((u8 *) next + 8) += *(s32 *) ((u8 *) list + 8);
                }
                func_802D6EB0(list);
                func_802D6EE0(list, arg0);
            }
        }
        list = next;
    }

    func_802D7660(savedState);
}

extern void *D_802E8CE0;
extern void *D_802E8CE4;
extern void *D_802E8CE8;
s32 func_802D7660(s32);

u16 func_80260210(u16 *arg0, u16 *arg1) {
    s32 savedState;
    u16 count1;
    u16 count2;
    u16 count3;
    void *list1;
    void *list2;
    void *list3;

    savedState = func_802D7660(1);

    list1 = D_802E8CE0;
    list2 = D_802E8CE8;
    list3 = D_802E8CE4;

    count1 = 0;
    if (list1 != NULL) {
        do {
            count1 = count1 + 1;
        } while ((list1 = *(void **) list1) != NULL);
    }

    count2 = 0;
    if (list2 != NULL) {
        do {
            count2 = count2 + 1;
        } while ((list2 = *(void **) list2) != NULL);
    }

    count3 = 0;
    if (list3 != NULL) {
        do {
            count3 = count3 + 1;
        } while ((list3 = *(void **) ((u8 *) list3 + 4)) != NULL);
    }

    *arg0 = count2;
    *arg1 = count1;

    func_802D7660(savedState);
    return count3;
}

/* TODO: func_80260300 - pop a node off the D_802E8CE8 free list (calling
 * func_802D6EB0 on it), link it onto the front of the D_802E8CE0 active
 * list (or make it the sole element of both D_802E8CE0 and D_802E8CE4 if
 * that list was empty), then initialize it from arg1 (stored at node+8)
 * and arg1->unk4 (byte fields at +3/+4/+5): flags at +0x36/+0x3e/+0x38,
 * a float at +0x2c=1.0 and +0x28=func_802D7610(arg1->unk4-derived
 * index*100 [+unk5 if a +0x3e flag bit is clear] - 0x1770), a "negative"
 * flag folded in from (arg1->unk0)->unk4==-1, and a handful of fixed
 * resets (+0x30, +0x3d, +0x3c, +0x34). Returns the node (NULL if the
 * free list was empty). Logic and every field/offset are confirmed
 * correct (down to a single differing opcode once the frame, instruction
 * count and register coloring are already exact). The one gap: in the
 * empty-active-list branch, target writes D_802E8CE0 and D_802E8CE4
 * (the same value, node) through a single shared `lui` - only possible
 * if both addresses come from the same relocation, i.e. the real source
 * reaches the second global via pointer arithmetic on the first rather
 * than naming it, but every arithmetic spelling tried
 * (`*((u8*)&D_802E8CE0+4)`, `*(&D_802E8CE0+1)`) made the front end
 * materialize the computed address as its own value first and then add
 * a second, redundant displacement, costing 2 instructions instead of
 * saving 1. Plain separate globals cost exactly the 1 extra `lui`
 * instead. */
#pragma GLOBAL_ASM("asm/nonmatchings/hd_code/17E10/func_80260300.s")

#pragma GLOBAL_ASM("asm/nonmatchings/hd_code/17E10/func_802604FC.s")

void func_80260618(void *arg0, u8 arg1) {
    if (arg0 != NULL) {
        *(s8 *)((u8 *) arg0 + 0x36) = (s8)(s16)(u8) arg1;
    }
}

u8 func_80260634(void *arg0) {
    if (arg0 != NULL) {
        return *(u8 *) ((u8 *) arg0 + 0x3f);
    }
    return 0;
}

extern s32 D_80358060;
extern s32 D_802E8BDC;
extern void *D_802E8CEC;
extern u8 D_80309124;
void *func_80260300(void *, void *);
s32 func_802D6C8C(void *, void *, s32);

void *func_80260650(void *arg0, s16 arg1, void *arg2) {
    void *node;
    void *result;
    void *entry4dead;
    void *entry;
    s16 flag1;
    s32 adjusted;
    s32 scaled;
    s32 totalSomething;
    s32 pad3;
    s32 pad4;
    s32 eventParam;
    s16 pad;
    s16 eventCode;
    s32 extra2;
    s32 extra1;
    s32 eventParam2;
    s16 pad2;
    s16 eventCode2;

    result = NULL;
    flag1 = 0;
    totalSomething = 0;
    if (arg1 == 0 || (D_80358060 == 0 && arg1 == 0xc)) {
        goto retNull;
    }
    if (arg1 == 0x14 || arg1 == 0x15) {
        if (D_802E8BDC == 0x26 || D_802E8BDC == 0x31) {
            goto retNull;
        }
    }
    goto mainLogic;

retNull:
    return NULL;

mainLogic:
    do {
        entry = *(void **) ((u8 *) (*(void **) ((u8 *) arg0 + 0xc))
            + (arg1 << 2) + 0xc);
        node = func_80260300(arg0, entry);
        if (node != NULL) {
            *(void **) ((u8 *) D_802E8CEC + 0x40) = node;
            eventCode = 1;
            eventParam = (s32) node;
            scaled = (s32) *(u8 *) ((u8 *) (*(void **) ((u8 *) entry + 4)) + 1)
                * 33333;

            if (*(u8 *) ((u8 *) node + 0x3e) & 0x10) {
                *(u8 *) ((u8 *) node + 0x3e) &= ~0x10;
                func_802D6C8C((u8 *) D_802E8CEC + 0x14, &eventCode,
                    totalSomething + 1);
                adjusted = scaled + 1;
                flag1 = arg1;
            } else {
                func_802D6C8C((u8 *) D_802E8CEC + 0x14, &eventCode,
                    scaled + 1);
            }
            result = node;
        } else {
            func_8029A7E4(&D_80309124, arg1);
        }

        totalSomething = totalSomething + scaled;
        entry4dead = *(void **) ((u8 *) entry + 4);
        arg1 = ((*(u8 *) ((u8 *) entry4dead + 2) & 0xc0) << 2)
            + *(u8 *) entry4dead;
    } while (arg1 != 0 && node != NULL);

    if (result != NULL) {
        *(u8 *) ((u8 *) result + 0x3e) |= 1;
        *(s32 *) ((u8 *) result + 0x30) = (s32) arg2;
        if (flag1 != 0) {
            *(u8 *) ((u8 *) result + 0x3e) |= 0x10;
            eventCode2 = 0x200;
            eventParam2 = (s32) result;
            extra1 = flag1;
            extra2 = (s32) arg0;
            func_802D6C8C((u8 *) D_802E8CEC + 0x14, &eventCode2, adjusted);
        }
    }

    if (arg2 != NULL) {
        *(void **) arg2 = result;
    }
    return result;
}

extern void *D_802E8CEC;
extern u8 D_8030914C;

s32 func_802D6C8C(void *, void *, s32);

/* eventTail/eventHead are dead stack space never read or written here - the
 * real source likely shares one ~0x10-byte event-record local across sites
 * like this one and only fills the leading eventCode/eventParam fields,
 * leaving the rest as reserved/unused padding (same shape as a plain array
 * would need, but writing it as one keeps the 0x24/0x20-offset slots from
 * ever materializing their own address, which doesn't match target). */
void func_802608C8(void *arg0) {
    s32 eventTail;
    s32 eventHead;
    s32 eventParam;
    s16 pad;
    s16 eventCode;

    eventCode = 0x400;
    eventParam = (s32) arg0;

    if (arg0 != NULL) {
        *((u8 *) arg0 + 0x3e) &= ~0x10;
        func_802D6C8C((u8 *) D_802E8CEC + 0x14, &eventCode, 0);
    } else {
        func_8029A7E4(&D_8030914C);
    }
}

extern void *D_802E8CE0;
s32 func_802D7660(s32);

void func_80260934(u8 arg0) {
    s32 savedState;
    s32 unused2;
    s32 unused1;
    s32 eventParam;
    s16 pad;
    s16 eventCode;
    void *entry;

    savedState = func_802D7660(1);
    entry = D_802E8CE0;
    if (entry != NULL) {
        do {
            eventCode = 0x400;
            eventParam = (s32) entry;
            if ((*((u8 *) entry + 0x3e) & arg0) == arg0) {
                *((u8 *) entry + 0x3e) &= ~0x10;
                func_802D6C8C((u8 *) D_802E8CEC + 0x14, &eventCode, 0);
            }
            entry = *(void **) entry;
        } while (entry != NULL);
    }
    func_802D7660(savedState);
}

void func_802609D0(void) {
    func_80260934(1);
}

void func_802609F0(void) {
    func_80260934(0x11);
}

void func_80260A10(void) {
    func_80260934(3);
}

void func_80260A30(u8 arg0) {
    s32 savedState;
    void *entry;
    s32 count;

    savedState = func_802D7660(1);
    entry = D_802E8CE0;
    count = 0;
    if (entry != NULL) {
        do {
            if ((*(u8 *) ((u8 *) (*(void **) ((u8 *) (*(void **) ((u8 *) entry + 8)) + 4)) + 2) & 0x3f) == arg0) {
                func_802608C8(entry);
            }
            count = count + 1;
        } while ((entry = *(void **) entry) != NULL);
    }
    func_802D7660(savedState);
}

extern u8 D_8030917C;

void func_80260AB8(void *arg0, s16 arg1, s32 arg2) {
    s32 unused;
    s32 eventExtra;
    s32 eventParam;
    s16 pad;
    s16 eventCode;

    eventCode = arg1;
    eventParam = (s32) arg0;
    eventExtra = arg2;

    if (arg0 != NULL) {
        func_802D6C8C((u8 *) D_802E8CEC + 0x14, &eventCode, 0);
    } else {
        func_8029A7E4(&D_8030917C);
    }
}

extern u16 *D_80366C28;

u16 func_80260B24(u8 arg0) {
    return D_80366C28[arg0];
}

extern void *D_802E8CE0;
extern void *D_802E8CEC;
s32 func_802D7660(s32);
s32 func_802D6C8C(void *, void *, s32);

void func_80260B40(u8 arg0, u16 arg1) {
    s32 savedState;
    void *entry;
    s32 count;
    s32 eventTail;
    s32 eventHead;
    s32 eventParam;
    s16 pad;
    s16 eventCode;

    savedState = func_802D7660(1);
    entry = D_802E8CE0;
    D_80366C28[arg0] = arg1;

    count = 0;
    while (entry != NULL) {
        if ((*(u8 *) ((u8 *) (*(void **) ((u8 *) (*(void **) ((u8 *) entry + 8)) + 4)) + 2) & 0x3f) == arg0) {
            eventCode = 0x800;
            eventParam = (s32) entry;
            func_802D6C8C((u8 *) D_802E8CEC + 0x14, &eventCode, 0);
        }
        count = count + 1;
        entry = *(void **) entry;
    }

    func_802D7660(savedState);
}
